version: 2
updates:
- package-ecosystem: npm
  directory: "/"
  schedule:
    interval: daily
  open-pull-requests-limit: 10
  ignore:
  - dependency-name: eslint
    versions:
    - 7.18.0
    - 7.19.0
    - 7.20.0
    - 7.21.0
    - 7.22.0
    - 7.23.0
    - 7.24.0
  - dependency-name: y18n
    versions:
    - 4.0.1
    - 4.0.2
  - dependency-name: "@typescript-eslint/eslint-plugin"
    versions:
    - 4.19.0
    - 4.20.0
    - 4.21.0
  - dependency-name: "@typescript-eslint/parser"
    versions:
    - 4.19.0
    - 4.20.0
    - 4.21.0
  - dependency-name: "@types/mini-css-extract-plugin"
    versions:
    - 1.4.0
    - 1.4.1
  - dependency-name: typescript
    versions:
    - 4.2.3
  - dependency-name: webpack-cli
    versions:
    - 4.4.0
    - 4.5.0
  - dependency-name: ini
    versions:
    - 1.3.7
    - 1.3.8
  - dependency-name: mini-css-extract-plugin
    versions:
    - 1.3.5
    - 1.3.6
    - 1.3.7
    - 1.3.8
    - 1.3.9
  - dependency-name: webpack-bundle-analyzer
    versions:
    - 4.4.0
  - dependency-name: eslint-plugin-prettier
    versions:
    - 3.3.1
  - dependency-name: webpack-node-externals
    versions:
    - 2.5.2
